theme: jekyll-theme-architect
title: 	7WStats - Wonders Score Sheet
description: 7WStats! Will become your assistant to calculate the victory points of 7 Wonders, your favorite board game.
show_downloads: true
